import type { Player } from '../types';

export const samplePlayers: Player[] = [
  {
    id: 'player-1',
    name: 'Virat Kohli',
    basePrice: 200,
    role: 'Batsman',
    rating: 95,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1pH0joh6VmIocGt1j3QYH-sc93mulJhae',
  },
  {
    id: 'player-2',
    name: 'Jasprit Bumrah',
    basePrice: 150,
    role: 'Bowler',
    rating: 92,
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=face',
  },
  {
    id: 'player-3',
    name: 'MS Dhoni',
    basePrice: 250,
    role: 'Wicket-Keeper',
    rating: 90,
    imageUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face',
  },
  {
    id: 'player-4',
    name: 'Hardik Pandya',
    basePrice: 180,
    role: 'All-Rounder',
    rating: 88,
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
  },
  {
    id: 'player-5',
    name: 'Rohit Sharma',
    basePrice: 220,
    role: 'Batsman',
    rating: 93,
  },
  {
    id: 'player-6',
    name: 'Rashid Khan',
    basePrice: 160,
    role: 'Bowler',
    rating: 89,
  },
  {
    id: 'player-7',
    name: 'KL Rahul',
    basePrice: 170,
    role: 'Wicket-Keeper',
    rating: 87,
  },
  {
    id: 'player-8',
    name: 'Ravindra Jadeja',
    basePrice: 190,
    role: 'All-Rounder',
    rating: 91,
  },
  {
    id: 'player-9',
    name: 'Shubman Gill',
    basePrice: 120,
    role: 'Batsman',
    rating: 85,
  },
  {
    id: 'player-10',
    name: 'Mohammed Shami',
    basePrice: 140,
    role: 'Bowler',
    rating: 86,
  },
  {
    id: 'player-11',
    name: 'Rishabh Pant',
    basePrice: 160,
    role: 'Wicket-Keeper',
    rating: 84,
  },
  {
    id: 'player-12',
    name: 'Washington Sundar',
    basePrice: 80,
    role: 'All-Rounder',
    rating: 78,
  },
  {
    id: 'player-13',
    name: 'Prithvi Shaw',
    basePrice: 100,
    role: 'Batsman',
    rating: 80,
  },
  {
    id: 'player-14',
    name: 'Yuzvendra Chahal',
    basePrice: 110,
    role: 'Bowler',
    rating: 82,
  },
  {
    id: 'player-15',
    name: 'Ishan Kishan',
    basePrice: 130,
    role: 'Wicket-Keeper',
    rating: 81,
  },
  {
    id: 'player-16',
    name: 'Krunal Pandya',
    basePrice: 90,
    role: 'All-Rounder',
    rating: 76,
  },
  {
    id: 'player-17',
    name: 'Shreyas Iyer',
    basePrice: 150,
    role: 'Batsman',
    rating: 83,
  },
  {
    id: 'player-18',
    name: 'Trent Boult',
    basePrice: 120,
    role: 'Bowler',
    rating: 88,
  },
  {
    id: 'player-19',
    name: 'Sanju Samson',
    basePrice: 110,
    role: 'Wicket-Keeper',
    rating: 79,
  },
  {
    id: 'player-20',
    name: 'Axar Patel',
    basePrice: 100,
    role: 'All-Rounder',
    rating: 77,
  },
  {
    id: 'player-21',
    name: 'Suryakumar Yadav',
    basePrice: 140,
    role: 'Batsman',
    rating: 86,
  },
  {
    id: 'player-22',
    name: 'Kagiso Rabada',
    basePrice: 130,
    role: 'Bowler',
    rating: 90,
  },
  {
    id: 'player-23',
    name: 'Jos Buttler',
    basePrice: 180,
    role: 'Wicket-Keeper',
    rating: 89,
  },
  {
    id: 'player-24',
    name: 'Marcus Stoinis',
    basePrice: 80,
    role: 'All-Rounder',
    rating: 74,
  },
  {
    id: 'player-25',
    name: 'Shikhar Dhawan',
    basePrice: 120,
    role: 'Batsman',
    rating: 81,
  },
  {
    id: 'player-26',
    name: 'Bhuvneshwar Kumar',
    basePrice: 90,
    role: 'Bowler',
    rating: 83,
  },
  {
    id: 'player-27',
    name: 'Dinesh Karthik',
    basePrice: 70,
    role: 'Wicket-Keeper',
    rating: 75,
  },
  {
    id: 'player-28',
    name: 'Glenn Maxwell',
    basePrice: 160,
    role: 'All-Rounder',
    rating: 85,
  },
];

export const defaultTeamNames = [
  'Mumbai Indians',
  'Chennai Super Kings', 
  'Royal Challengers Bangalore',
  'Kolkata Knight Riders',
  'Delhi Capitals',
  'Punjab Kings',
  'Rajasthan Royals',
  'Sunrisers Hyderabad',
  'Gujarat Titans',
  'Lucknow Super Giants',
  'Team 11',
  'Team 12',
  'Team 13', 
  'Team 14',
  'Team 15',
  'Team 16'
];
